export const TYPES = {
  App: Symbol.for("App"),
  Logger: Symbol.for("Logger"),
  ExceptionFilter: Symbol.for("ExceptionFilter"),
  UserController: Symbol.for("UserController"),
  PostController: Symbol.for("PostController"),
  CommentController: Symbol.for("CommentController"),
  MongoService: Symbol.for("MongoService"),
  ConfigService: Symbol.for("ConfigService"),
  UserService: Symbol.for("UserService"),
  UserRepository: Symbol.for("UserRepository"),
  CommentService: Symbol.for("CommentService"),
  CommentRepository: Symbol.for("CommentRepository"),
  PostService: Symbol.for("PostService"),
  PostRepository: Symbol.for("PostRepository"),
};
